compatibility_date = "2023-10-16"
name = "worker-template"
workers_dev = true
routes = []
vars = { }
main = "./dist/_worker.js"


[build]
command = "npm install && npm run build"

[env.production]
workers_dev = false
vars = {  }
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[env.local]
workers_dev = true
routes = []
vars = { adminSecret = "adminSecret" }
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[env.local.build]
command = ""


[dev]
host = "example.com"
port = 8787
