compatibility_date = "2023-01-11"
name = "worker-template"
workers_dev = true
routes = []
vars = { }
main = "./dist/_worker.js"


[build]
command = "npm install && npm run build"

[env.production]
workers_dev = false
vars = {  }
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[env.local]
workers_dev = true
vars = { adminSecret = "adminSecret" }
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
port = 8788
