compatibility_date = "2023-03-13"
type = "javascript"
name = "worker-template"
workers_dev = true
routes = []
vars = { }
port = 8787

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./_worker.js"

[env.miniflare]
vars = { }

[miniflare]
durable_objects_persist = "./.miniflare/durable-objects/"
kv_persist = "./.miniflare/kv/"
