compatibility_date = "2024-12-30"
name = "worker-template"
workers_dev = true
routes = []
vars = {}
main = "./index.ts"
minify = true
upload_source_maps = true


[env.production]
vars = {}
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[env.local]
routes = []
vars = { adminSecret = "adminSecret" }
durable_objects.bindings = []
kv_namespaces = []
r2_buckets = []

[dev]
host = "example.com"
port = 8787
